networks:
  hls:
    driver: bridge

services:
  api-server:
    build:
      context: ./api-server
    container_name: api-server
    depends_on:
      - redis
    env_file:
      - ./api-server/.env
    networks:
      - hls
    ports:
      - "9001:9001"
      - "9000:9000"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hls
